name: test

on:
  push:
    branches: [ develop ]

jobs:
  test: 
    runs-on: ubuntu-latest 
    steps:
    - name: Run a one-line script
      run: echo Hello World!
    - name: Run pwd
      run: pwd
