spring:
  profiles:
    active: sgkim
---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  config:
    activate:
      on-profile: sgkim


mybatis:
  type-aliases-package: com.flab.demo.dto, com.flab.demo.domain
  mapper-locations: classpath:mapper/**.xml

  configuration:
    map-underscore-to-camel-case: true
