spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 6000
