version: '2'

services:
  redis:
    container_name: "redis"
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./volume/shopandsave-redis-volume:/data
      - ./volume/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./volume/acl/users/acl:/etc/redis/users.acl
    command: redis-server /usr/local/etc/redis/redis.conf

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - ./volume/shopandsave-mysql-volume:/var/lib/mysql
    restart: always
    container_name: shopandsave_mysql
    environment:
      MYSQL_ROOT_PASSWORD: baesuyeon
      MYSQL_DATABASE: shopandsave
      MYSQL_USER: admin
      MYSQL_PASSWORD: baesuyeon
    ports:
      - "3308:3306"